/**
 * Shell manifest generation for --add-dir workflow.
 *
 * @module @libar-dev/modular-claude-md/additive/manifest
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { Metadata } from "../types.js";
import { log } from "../utils/colors.js";

/**
 * Entry in the generated manifest.
 */
export interface ManifestEntry {
  name: string;
  alias: string;
  addDirPath: string;
  description: string | undefined;
}

/**
 * Generate manifest entries from additive variations.
 */
export function generateManifestEntries(metadata: Metadata): ManifestEntry[] {
  if (!metadata.additive_variations) {
    return [];
  }

  return metadata.additive_variations.map((layer) => ({
    name: layer.name,
    alias: `claude-${layer.name}`,
    addDirPath: layer.output_dir,
    description: layer.description,
  }));
}

/**
 * Generate shell manifest content.
 *
 * @param metadata - The metadata configuration
 * @returns Shell script content
 */
export function generateManifestContent(metadata: Metadata): string {
  const entries = generateManifestEntries(metadata);
  const lines: string[] = [];

  lines.push("#!/usr/bin/env bash");
  lines.push("#");
  lines.push("# Claude Code Layer Manifest");
  lines.push("# Generated by @libar-dev/modular-claude-md");
  lines.push("#");
  lines.push("# Source this file to get shell aliases for --add-dir workflow:");
  lines.push("#   source .claude-layers/manifest.sh");
  lines.push("#");
  lines.push("");

  // Environment variable
  lines.push("# Enable Claude Code additional directories feature");
  lines.push("export CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD=1");
  lines.push("");

  // Individual layer aliases
  lines.push("# Layer-specific aliases");
  for (const entry of entries) {
    if (entry.description) {
      lines.push(`# ${entry.description}`);
    }
    lines.push(`alias ${entry.alias}="claude --add-dir ${entry.addDirPath}"`);
  }
  lines.push("");

  // Full context alias (all layers)
  if (entries.length > 0) {
    const allDirs = entries.map((e) => `--add-dir ${e.addDirPath}`).join(" ");
    lines.push("# Load all layers");
    lines.push(`alias claude-full="claude ${allDirs}"`);
    lines.push("");
  }

  // Helper function
  lines.push("# Function to load specific layers by name");
  lines.push("# Usage: claude-with delivery-process testing");
  lines.push("claude-with() {");
  lines.push('  local dirs=""');
  lines.push('  for layer in "$@"; do');
  lines.push('    dirs="$dirs --add-dir .claude-layers/$layer"');
  lines.push("  done");
  lines.push("  claude $dirs");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Write the manifest file.
 *
 * @param metadata - The metadata configuration
 * @param projectRoot - Project root directory
 * @param preview - If true, don't write files
 * @returns Path to manifest file
 */
export function writeManifest(
  metadata: Metadata,
  projectRoot: string,
  preview: boolean = false
): string {
  const content = generateManifestContent(metadata);
  const manifestPath = path.join(projectRoot, ".claude-layers", "manifest.sh");

  if (preview) {
    log(`Would write: ${manifestPath}`, "dim");
    log(`Content (${content.length} bytes):`, "dim");
    console.log(content);
  } else {
    // Ensure directory exists
    const dir = path.dirname(manifestPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(manifestPath, content, "utf-8");
    // Make executable
    fs.chmodSync(manifestPath, 0o755);
    log(`Written: ${manifestPath}`, "green");
  }

  return manifestPath;
}
